baseURL = "http://example.org/"
languageCode = "en-us"
title = "JoymonOnline"
theme = "ananke"
[menu]
[[menu.main]]
    identifier = "Home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = -1110
[[menu.main]]
    identifier = "Resume"
    name = "Resume"
    pre = "<i class='fa fa-heart'></i>"
    url = "/resume"
    weight = -50