baseURL = "https://joymon.github.io/site-hugo"
languageCode = "en-us"
title = "JoymonOnline"
theme ="jo-black"
show_reading_time = true
copyright ="Copyright © 2020 Joy George K."
[params]
 description = "Personal information site of Joy George K nicknamed Joymon.This contains my personal ,educational and professionsl details"
 subtitle = "Know me more..."
 author ="Joy George K"
 contact = "joymon@gmail.com"
 keywords = "Joymon, Joymon Online, Joy George K, Kunjikkuru House"
[menu]
 [[menu.main]]
  identifier ="Home"
  name="Home"
  pre="<i class='fa fa-home'></i>"
  url="/"
  weight="1"