baseURL = "https://joymon.github.io/site-hugo"
languageCode = "en-us"
title = "JoymonOnline"
theme ="jo-black"
show_reading_time = true
[params]
 description = "Know me more..."
[menu]
 [[menu.main]]
  identifier ="Home"
  name="Home"
  pre="<i class='fa fa-heart'></i>"
  url="/"
  weight="1"